export const weatherCodeLabel: Record<number, string> = {
  0: "Clear",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Rime fog",
  51: "Light drizzle",
  53: "Drizzle",
  55: "Dense drizzle",
  56: "Freezing drizzle",
  57: "Freezing drizzle",
  61: "Light rain",
  63: "Rain",
  65: "Heavy rain",
  66: "Freezing rain",
  67: "Freezing rain",
  71: "Light snow",
  73: "Snow",
  75: "Heavy snow",
  77: "Snow grains",
  80: "Rain showers",
  81: "Heavy showers",
  82: "Violent showers",
  85: "Snow showers",
  86: "Snow showers",
  95: "Thunderstorm",
  96: "Thunderstorm with hail",
  99: "Thunderstorm with hail",
}

export const weatherCodeIcon: Record<number, string> = {
  0: "weather-clear-symbolic",
  1: "weather-few-clouds-symbolic",
  2: "weather-few-clouds-symbolic",
  3: "weather-overcast-symbolic",
  45: "weather-fog-symbolic",
  48: "weather-fog-symbolic",
  51: "weather-showers-scattered-symbolic",
  53: "weather-showers-scattered-symbolic",
  55: "weather-showers-symbolic",
  56: "weather-showers-symbolic",
  57: "weather-showers-symbolic",
  61: "weather-showers-symbolic",
  63: "weather-showers-symbolic",
  65: "weather-showers-symbolic",
  66: "weather-showers-symbolic",
  67: "weather-showers-symbolic",
  71: "weather-snow-symbolic",
  73: "weather-snow-symbolic",
  75: "weather-snow-symbolic",
  77: "weather-snow-symbolic",
  80: "weather-showers-scattered-symbolic",
  81: "weather-showers-symbolic",
  82: "weather-showers-symbolic",
  95: "weather-storm-symbolic",
  96: "weather-storm-symbolic",
  99: "weather-storm-symbolic",
}
