import css from "./styles.css"

export { css }
export { AegisWindow } from "./windows/AegisWindow"
export { AegisWidget } from "./widgets/AegisWidget"
export { AegisSummaryWidget } from "./widgets/AegisSummaryWidget"
export { AegisDiskWidget } from "./widgets/AegisDiskWidget"
export { AegisMemoryWidget } from "./widgets/AegisMemoryWidget"
export { AegisNetworkWidget } from "./widgets/AegisNetworkWidget"
export { AegisBatteryWidget } from "./widgets/AegisBatteryWidget"
export { AegisDiskPieWidget } from "./widgets/DiskPieWidget"
export { AegisMemoryPieWidget } from "./widgets/MemoryPieWidget"
export { AegisCpuGraphWidget } from "./widgets/AegisCpuGraphWidget"
export { getSysinfoService } from "./services/sysinfo"
export type { AegisMode, SysinfoModel } from "./types"
export type { SectionId } from "./widgets/sections"
